@server=http://localhost:4004
@username=alice
@password=


### Products
# @name Products_GET
GET {{server}}/admin/Products
Authorization: Basic {{username}}:{{password}}

### Products
# @name Products_POST
POST {{server}}/admin/Products
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "79697031-0059-44b3-92ef-bed9b4165cb4",
  "title": "Install package 'randexp' to create data for regex ^[A-Za-z0-9. ]",
  "description": "Install package 'randexp' to create data for regex ^[A-Za-z0-9. ]",
  "price": 16.95,
  "stock": 14,
  "expiryDate": "2007-10-28",
  "reviews": [
    {
      "ID": "26510834-e337-4e60-95b5-bc095d7b02a5",
      "createdAt": "2017-07-28T22:00:00.000Z",
      "createdBy": "createdBy.fs7w2@example.org",
      "modifiedAt": "2005-09-21T22:00:00.000Z",
      "modifiedBy": "modifiedBy.fs7w2@example.org",
      "reviewer": {
        "ID": "2103706e-498d-482e-846b-8329d4cb8699"
      },
      "rating": 100.09,
      "comment": "comment-26510834"
    },
    {
      "ID": "26510835-6204-4094-ac24-5c60c632bc80",
      "createdAt": "2022-04-24T22:00:00.000Z",
      "createdBy": "createdBy.fs7w3@example.net",
      "modifiedAt": "2003-03-21T22:00:00.000Z",
      "modifiedBy": "modifiedBy.fs7w3@example.net",
      "reviewer": {
        "ID": "2103706e-498d-482e-846b-8329d4cb8699"
      },
      "rating": 76.28,
      "comment": "comment-26510835"
    }
  ],
  "createdAt": "2009-06-17T22:00:00.000Z",
  "createdBy": "createdBy.4qtgn@example.org",
  "modifiedAt": "2010-04-05T22:00:00.000Z",
  "modifiedBy": "modifiedBy.4qtgn@example.org"
}


### Products
# @name Products_PATCH
PATCH {{server}}/admin/Products/79697031-0059-44b3-92ef-bed9b4165cb4
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "79697031-0059-44b3-92ef-bed9b4165cb4",
  "title": "Install package 'randexp' to create data for regex ^[A-Za-z0-9. ]",
  "description": "Install package 'randexp' to create data for regex ^[A-Za-z0-9. ]",
  "price": 16.95,
  "stock": 14,
  "expiryDate": "2007-10-28",
  "reviews": [
    {
      "ID": "26510834-e337-4e60-95b5-bc095d7b02a5",
      "createdAt": "2017-07-28T22:00:00.000Z",
      "createdBy": "createdBy.fs7w2@example.org",
      "modifiedAt": "2005-09-21T22:00:00.000Z",
      "modifiedBy": "modifiedBy.fs7w2@example.org",
      "reviewer": {
        "ID": "2103706e-498d-482e-846b-8329d4cb8699"
      },
      "rating": 100.09,
      "comment": "comment-26510834"
    },
    {
      "ID": "26510835-6204-4094-ac24-5c60c632bc80",
      "createdAt": "2022-04-24T22:00:00.000Z",
      "createdBy": "createdBy.fs7w3@example.net",
      "modifiedAt": "2003-03-21T22:00:00.000Z",
      "modifiedBy": "modifiedBy.fs7w3@example.net",
      "reviewer": {
        "ID": "2103706e-498d-482e-846b-8329d4cb8699"
      },
      "rating": 76.28,
      "comment": "comment-26510835"
    }
  ],
  "createdAt": "2009-06-17T22:00:00.000Z",
  "createdBy": "createdBy.4qtgn@example.org",
  "modifiedAt": "2010-04-05T22:00:00.000Z",
  "modifiedBy": "modifiedBy.4qtgn@example.org"
}


### Products
# @name Products_DELETE
DELETE {{server}}/admin/Products/79697031-0059-44b3-92ef-bed9b4165cb4
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### User
# @name User_GET
GET {{server}}/admin/User
Authorization: Basic {{username}}:{{password}}


### User
# @name User_POST
POST {{server}}/admin/User
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "2103706e-498d-482e-846b-8329d4cb8699",
  "names": "names-2103706",
  "email": "email-2103706",
  "createdAt": "2011-02-27T22:00:00.000Z",
  "createdBy": "createdBy.1938a@example.net",
  "modifiedAt": "2002-07-08T22:00:00.000Z",
  "modifiedBy": "modifiedBy.1938a@example.com"
}


### User
# @name User_PATCH
PATCH {{server}}/admin/User/2103706e-498d-482e-846b-8329d4cb8699
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "2103706e-498d-482e-846b-8329d4cb8699",
  "names": "names-2103706",
  "email": "email-2103706",
  "createdAt": "2011-02-27T22:00:00.000Z",
  "createdBy": "createdBy.1938a@example.net",
  "modifiedAt": "2002-07-08T22:00:00.000Z",
  "modifiedBy": "modifiedBy.1938a@example.com"
}


### User
# @name User_DELETE
DELETE {{server}}/admin/User/2103706e-498d-482e-846b-8329d4cb8699
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Orders
# @name Orders_GET
GET {{server}}/admin/Orders
Authorization: Basic {{username}}:{{password}}


### Orders
# @name Orders_POST
POST {{server}}/admin/Orders
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "31433655-f5fe-4cfd-9b4c-a82a480b1df8",
  "customer": {
    "ID": "2103706e-498d-482e-846b-8329d4cb8699"
  },
  "items": [
    {
      "ID": "55856578-4c6e-4809-b8d5-bb2894b4af6e",
      "createdAt": "2006-06-06T22:00:00.000Z",
      "createdBy": "createdBy.3bpx5@example.org",
      "modifiedAt": "2008-03-13T22:00:00.000Z",
      "modifiedBy": "modifiedBy.3bpx5@example.net",
      "product": {
        "ID": "79697031-0059-44b3-92ef-bed9b4165cb4"
      },
      "quantity": 71,
      "unit_price": 58.96
    },
    {
      "ID": "55856580-d4cd-4869-b535-b4e3db1e7d9c",
      "createdAt": "2006-06-16T22:00:00.000Z",
      "createdBy": "createdBy.3bpx6@example.net",
      "modifiedAt": "2016-08-27T22:00:00.000Z",
      "modifiedBy": "modifiedBy.3bpx6@example.net",
      "product": {
        "ID": "79697031-0059-44b3-92ef-bed9b4165cb4"
      },
      "quantity": 44,
      "unit_price": 34.54
    }
  ],
  "totalPrice": 96.45,
  "status": "Cancelled",
  "createdAt": "2019-01-21T22:00:00.000Z",
  "createdBy": "createdBy.ipqd3@example.net",
  "modifiedAt": "2002-08-11T22:00:00.000Z",
  "modifiedBy": "modifiedBy.ipqd3@example.net"
}


### Orders
# @name Orders_PATCH
PATCH {{server}}/admin/Orders/31433655-f5fe-4cfd-9b4c-a82a480b1df8
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "31433655-f5fe-4cfd-9b4c-a82a480b1df8",
  "customer": {
    "ID": "2103706e-498d-482e-846b-8329d4cb8699"
  },
  "items": [
    {
      "ID": "55856578-4c6e-4809-b8d5-bb2894b4af6e",
      "createdAt": "2006-06-06T22:00:00.000Z",
      "createdBy": "createdBy.3bpx5@example.org",
      "modifiedAt": "2008-03-13T22:00:00.000Z",
      "modifiedBy": "modifiedBy.3bpx5@example.net",
      "product": {
        "ID": "79697031-0059-44b3-92ef-bed9b4165cb4"
      },
      "quantity": 71,
      "unit_price": 58.96
    },
    {
      "ID": "55856580-d4cd-4869-b535-b4e3db1e7d9c",
      "createdAt": "2006-06-16T22:00:00.000Z",
      "createdBy": "createdBy.3bpx6@example.net",
      "modifiedAt": "2016-08-27T22:00:00.000Z",
      "modifiedBy": "modifiedBy.3bpx6@example.net",
      "product": {
        "ID": "79697031-0059-44b3-92ef-bed9b4165cb4"
      },
      "quantity": 44,
      "unit_price": 34.54
    }
  ],
  "totalPrice": 96.45,
  "status": "Cancelled",
  "createdAt": "2019-01-21T22:00:00.000Z",
  "createdBy": "createdBy.ipqd3@example.net",
  "modifiedAt": "2002-08-11T22:00:00.000Z",
  "modifiedBy": "modifiedBy.ipqd3@example.net"
}


### Orders
# @name Orders_DELETE
DELETE {{server}}/admin/Orders/31433655-f5fe-4cfd-9b4c-a82a480b1df8
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### OrderItems
# @name OrderItems_GET
GET {{server}}/admin/OrderItems
Authorization: Basic {{username}}:{{password}}


### OrderItems
# @name OrderItems_POST
POST {{server}}/admin/OrderItems
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "55856578-4c6e-4809-b8d5-bb2894b4af6e",
  "createdAt": "2006-06-06T22:00:00.000Z",
  "createdBy": "createdBy.3bpx5@example.org",
  "modifiedAt": "2008-03-13T22:00:00.000Z",
  "modifiedBy": "modifiedBy.3bpx5@example.net",
  "product": {
    "ID": "79697031-0059-44b3-92ef-bed9b4165cb4"
  },
  "quantity": 71,
  "unit_price": 58.96
}


### OrderItems
# @name OrderItems_PATCH
PATCH {{server}}/admin/OrderItems(up_=[object Object],ID=55856578-4c6e-4809-b8d5-bb2894b4af6e)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "55856578-4c6e-4809-b8d5-bb2894b4af6e",
  "createdAt": "2006-06-06T22:00:00.000Z",
  "createdBy": "createdBy.3bpx5@example.org",
  "modifiedAt": "2008-03-13T22:00:00.000Z",
  "modifiedBy": "modifiedBy.3bpx5@example.net",
  "product": {
    "ID": "79697031-0059-44b3-92ef-bed9b4165cb4"
  },
  "quantity": 71,
  "unit_price": 58.96
}


### OrderItems
# @name OrderItems_DELETE
DELETE {{server}}/admin/OrderItems(up_=[object Object],ID=55856578-4c6e-4809-b8d5-bb2894b4af6e)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
