@server=http://localhost:4004
@username=alice
@password=


### Products
# @name Products_GET
GET {{server}}/browse/Products
Authorization: Basic {{username}}:{{password}}


### Reviews
# @name Reviews_GET
GET {{server}}/browse/Reviews
Authorization: Basic {{username}}:{{password}}


### Reviews
# @name Reviews_POST
POST {{server}}/browse/Reviews
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "82928106-5ac5-4d05-87a1-d3defbeedf14",
  "createdAt": "2009-01-03T22:00:00.000Z",
  "createdBy": "createdBy.4xqru@example.org",
  "modifiedAt": "2020-10-03T22:00:00.000Z",
  "modifiedBy": "modifiedBy.4xqru@example.net",
  "rating": 65.72,
  "comment": "comment-8292810"
}


### Reviews
# @name Reviews_PATCH
PATCH {{server}}/browse/Reviews(up_=[object Object],ID=82928106-5ac5-4d05-87a1-d3defbeedf14)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "82928106-5ac5-4d05-87a1-d3defbeedf14",
  "createdAt": "2009-01-03T22:00:00.000Z",
  "createdBy": "createdBy.4xqru@example.org",
  "modifiedAt": "2020-10-03T22:00:00.000Z",
  "modifiedBy": "modifiedBy.4xqru@example.net",
  "rating": 65.72,
  "comment": "comment-8292810"
}


### Reviews
# @name Reviews_DELETE
DELETE {{server}}/browse/Reviews(up_=[object Object],ID=82928106-5ac5-4d05-87a1-d3defbeedf14)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Orders
# @name Orders_GET
GET {{server}}/browse/Orders
Authorization: Basic {{username}}:{{password}}


### Orders
# @name Orders_POST
POST {{server}}/browse/Orders
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "30424626-47f0-480e-9bfd-57b2747c56e3",
  "items": [
    {
      "ID": "27761554-93e4-485f-b5a7-31f6c172b1b7",
      "createdAt": "2022-02-11T22:00:00.000Z",
      "createdBy": "createdBy.gj0ya@example.org",
      "modifiedAt": "2001-09-13T22:00:00.000Z",
      "modifiedBy": "modifiedBy.gj0ya@example.com",
      "product": {
        "ID": "43984800-72a8-4e94-9377-1a2967057213"
      },
      "quantity": 98,
      "unit_price": 51.66
    },
    {
      "ID": "27761555-e263-49e2-99b6-257d55c3d9dd",
      "createdAt": "2009-01-22T22:00:00.000Z",
      "createdBy": "createdBy.gj0yb@example.net",
      "modifiedAt": "2014-03-09T22:00:00.000Z",
      "modifiedBy": "modifiedBy.gj0yb@example.net",
      "product": {
        "ID": "43984800-72a8-4e94-9377-1a2967057213"
      },
      "quantity": 79,
      "unit_price": 65.43
    }
  ],
  "totalPrice": 25.11,
  "status": "Completed",
  "createdAt": "2014-01-26T22:00:00.000Z",
  "createdBy": "createdBy.i43si@example.org",
  "modifiedAt": "2011-04-15T22:00:00.000Z",
  "modifiedBy": "modifiedBy.i43si@example.org"
}


### Orders
# @name Orders_PATCH
PATCH {{server}}/browse/Orders/30424626-47f0-480e-9bfd-57b2747c56e3
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "30424626-47f0-480e-9bfd-57b2747c56e3",
  "items": [
    {
      "ID": "27761554-93e4-485f-b5a7-31f6c172b1b7",
      "createdAt": "2022-02-11T22:00:00.000Z",
      "createdBy": "createdBy.gj0ya@example.org",
      "modifiedAt": "2001-09-13T22:00:00.000Z",
      "modifiedBy": "modifiedBy.gj0ya@example.com",
      "product": {
        "ID": "43984800-72a8-4e94-9377-1a2967057213"
      },
      "quantity": 98,
      "unit_price": 51.66
    },
    {
      "ID": "27761555-e263-49e2-99b6-257d55c3d9dd",
      "createdAt": "2009-01-22T22:00:00.000Z",
      "createdBy": "createdBy.gj0yb@example.net",
      "modifiedAt": "2014-03-09T22:00:00.000Z",
      "modifiedBy": "modifiedBy.gj0yb@example.net",
      "product": {
        "ID": "43984800-72a8-4e94-9377-1a2967057213"
      },
      "quantity": 79,
      "unit_price": 65.43
    }
  ],
  "totalPrice": 25.11,
  "status": "Completed",
  "createdAt": "2014-01-26T22:00:00.000Z",
  "createdBy": "createdBy.i43si@example.org",
  "modifiedAt": "2011-04-15T22:00:00.000Z",
  "modifiedBy": "modifiedBy.i43si@example.org"
}


### Orders
# @name Orders_DELETE
DELETE {{server}}/browse/Orders/30424626-47f0-480e-9bfd-57b2747c56e3
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### OrderItems
# @name OrderItems_GET
GET {{server}}/browse/OrderItems
Authorization: Basic {{username}}:{{password}}


### OrderItems
# @name OrderItems_POST
POST {{server}}/browse/OrderItems
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "27761554-93e4-485f-b5a7-31f6c172b1b7",
  "createdAt": "2022-02-11T22:00:00.000Z",
  "createdBy": "createdBy.gj0ya@example.org",
  "modifiedAt": "2001-09-13T22:00:00.000Z",
  "modifiedBy": "modifiedBy.gj0ya@example.com",
  "product": {
    "ID": "43984800-72a8-4e94-9377-1a2967057213"
  },
  "quantity": 98,
  "unit_price": 51.66
}


### OrderItems
# @name OrderItems_PATCH
PATCH {{server}}/browse/OrderItems(up_=[object Object],ID=27761554-93e4-485f-b5a7-31f6c172b1b7)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "27761554-93e4-485f-b5a7-31f6c172b1b7",
  "createdAt": "2022-02-11T22:00:00.000Z",
  "createdBy": "createdBy.gj0ya@example.org",
  "modifiedAt": "2001-09-13T22:00:00.000Z",
  "modifiedBy": "modifiedBy.gj0ya@example.com",
  "product": {
    "ID": "43984800-72a8-4e94-9377-1a2967057213"
  },
  "quantity": 98,
  "unit_price": 51.66
}


### OrderItems
# @name OrderItems_DELETE
DELETE {{server}}/browse/OrderItems(up_=[object Object],ID=27761554-93e4-485f-b5a7-31f6c172b1b7)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
